### ISSUE TITLE
Add in quotedb support

### ISSUE THREAD

**Issue by MattDees** [MattDees/GeckBot#9]
Quote DB support.

These quotes are primarily meant for setting quotes for people, but we can also set quotes for figures.

a quote can be set by:

    !quote $key $string

and quote can be retrieved with:

    !quote $key

This corresponds to a DB like:

quotes

    quote_id int 16
    key varchar 64
    channel_id int 16
    quote varchar 160

when a quote is looked up, it's looked up by:

SELECT quote FROM quotes WHERE channel_id=$channel_id AND key=$key

When a quote is set, it is an INSERT not a update_or_create.  meaning that a single key may have multiple quotes and I'll need to work out how to pull a random one.

(via DBIx, of course)

**Comment by JPerkster** [comment]
This was done in aecbd6967aa3d2a6b864a01af93cab918e7b4d8c
